server:
  port: 8060

spring:
  datasource:
    username: root
    password: 991002
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: discountService

mybatis:
  #domain对象的包
  type-aliases-package: com.xmu.discount
  #mapper.xml所在的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

eureka:
  client:
    service-url:
      defaultZone: http://172.81.212.62:7001/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true